### ISSUE TITLE
This should be usable as a GitHub Action

### ISSUE THREAD

**Issue by j3parker** [Brightspace/render-docs-action#4]
A repo should be able to consume this tool as an action:

```
    - uses: actions/checkout@v2
    - name: Build
      uses: Brightspace/render-docs-action@master
      with:
        dir: docs/
        path: path/on/site
    - name: Upload
       run: aws s3 sync --delete s3://d2l.dev/path/on/site/ docs/
       env:
          ... AWS SECRETS ...
```

The action would need to take the dir to find the docs (optional - default to `./`?) and the path as it will be rooted on docs.d2l.dev.
